Sprint 1
AntonVolkov71/middle.messenger.praktikum.yandex pull request #1
Opened 2022-07-25 14:56 UTC by AntonVolkov71

2022-07-25 15:31 UTC, podlovchenko requested changes
Привет, в целом все хорошо, есть несколько замечаний
1. Приложение не на 3000 порту
2. Нет ссылок на нетлифай и фигму
3. Команда старт должна запускать сервер, а для разработки можно использовать запуск parcel
4. Привести код в порядок (убрать ошибки EOF, лишние строки, исправить ошибки линтера, убрать лишние папки из репозитория)

2022-07-25 15:31 UTC, podlovchenko commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Папки .idea и dist не должно быть в проекте, нужно завести файл .gitignore

2022-07-25 15:31 UTC, podlovchenko commented on .parcelrc
> +}
Во многих файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-07-25 15:31 UTC, podlovchenko commented on README.md
> +
В ридми не хватает ссылки на нетлифай и макеты в фигме

2022-07-25 15:31 UTC, podlovchenko commented on package.json
> +    "start": "parcel src/index.html --no-source-maps --target default --dist-dir ./build",
Приложение должно запускаться на 3000 порту, для этого нужно добавить флаг --port

2022-07-25 15:31 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-inline-string": "^2.4.1",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-07-25 15:31 UTC, podlovchenko commented on src/app.js
> +const defaultPort = 3333;
Должен быть 3000 порт

2022-07-25 15:31 UTC, podlovchenko commented on src/components/active-chat/index.js
> +export default (props = {}) => tpl(props);
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-07-25 15:31 UTC, podlovchenko commented on src/components/open-profile/style.scss
> +    span {
Лучше использовать классы, а не теги
Статься на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-07-25 15:31 UTC, podlovchenko commented on src/partials/message/style.scss
> +
Лишние строки

2022-07-25 15:31 UTC, podlovchenko commented on src/styles/app/card.scss
> +  box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.14);
Лучше все цвета указывать через переменные, так их будет проще редактировать по всему проекту

2022-07-25 16:31 UTC, AntonVolkov71 commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
+

2022-07-25 16:31 UTC, AntonVolkov71 commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
++

2022-07-25 16:32 UTC, AntonVolkov71 commented on package.json
> +    "start": "parcel src/index.html --no-source-maps --target default --dist-dir ./build",
++

2022-07-25 16:34 UTC, AntonVolkov71 commented on src/app.js
> +const defaultPort = 3333;
++

2022-07-25 16:35 UTC, AntonVolkov71 commented on package.json
> +    "@parcel/transformer-inline-string": "^2.4.1",
++

2022-07-25 16:56 UTC, AntonVolkov71 commented on src/components/active-chat/index.js
> +export default (props = {}) => tpl(props);
++

2022-07-25 16:58 UTC, AntonVolkov71 commented on src/components/open-profile/style.scss
> +    span {
++

2022-07-25 16:58 UTC, AntonVolkov71 commented on src/partials/message/style.scss
> +
++

2022-07-25 17:00 UTC, AntonVolkov71 commented on src/styles/app/card.scss
> +  box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.14);
++

2022-07-25 18:05 UTC, AntonVolkov71 commented on .parcelrc
> +}
++

2022-07-25 18:05 UTC, AntonVolkov71 commented on README.md
> +
++

2022-07-26 08:58 UTC, podlovchenko requested changes
Привет, в репозитории все еще есть лишние папки .idea и build, не хватает ссылки на фигму и есть ошибки eslint

2022-07-26 08:58 UTC, podlovchenko commented on src/index.js
> +import emptyChats from './partials/empty-chats';
button и emptyChats здесь не используются

2022-07-26 18:21 UTC, AntonVolkov71 commented on src/index.js
> +import emptyChats from './partials/empty-chats';
++ ссылки на все в main ветке
и также добавлены в в ветку sprint_1 в Readme -> #### Макет сего чуда

2022-07-27 06:59 UTC, podlovchenko approved these changes
Работу принимаю)

2022-07-27 06:59 UTC, podlovchenko commented on src/modules/handlers/index.js
> +// export default handlers;
Закомментированный код лучше не оставлять в репозитории

2022-07-30 12:00 UTC, AntonVolkov71 commented on src/modules/handlers/index.js
> +// export default handlers;
++

2022-07-30 12:03 UTC, merged